package com.ickik.ladder.model;

public enum RightsFunction {

	ADD_CATEGORY(1),
	ADD_VERSION(11),
	CHOOSE_DIRECTORY(21),
	SEARCH_IN_DIRECTORY(22),
	SELECT_ALL(23),
	EXECUTE(24),
	ADD_XML_FILE(31),
	ADD_TEST_CLASS(41),
	TC_VIEW_CATEGORY(51),
	TC_VIEW_XML_TEST_FILE(52),
	TC_VIEW_TEST_CLASS(53),
	TC_VIEW_METHOD(54),
	TC_VIEW_DESCRIPTION(55),
	TC_VIEW_TEST_CASE(56),
	TC_VIEW_STATE(57),
	TC_VIEW_VERSION(58),
	TC_VIEW_DATE_CREATION(59),
	TC_VIEW_USER_CREATION(60),
	TC_VIEW_LAST_MODIFIED_VERSION(61),
	TC_VIEW_LAST_MODIFIED_USER(62),
	TC_VIEW_LAST_MODIFIED_DATE(63),
	TC_INSERTION(66),
	TC_MODIFY(67),
	TC_SEARCH(68),
	TC_CLEAN(69),
	TE_VIEW_CATEGORY(81),
	TE_VIEW_XML_TEST_FILE(82),
	TE_VIEW_TEST_CLASS(83),
	TE_VIEW_METHOD(84),
	TE_VIEW_DESCRIPTION(85),
	TE_VIEW_TEST_CASE(86),
	TE_VIEW_STATE(87),
	TE_VIEW_VERSION(88),
	TE_VIEW_DATE_CREATION(89),
	TE_VIEW_USER_CREATION(90),
	TE_VIEW_LAST_MODIFIED_VERSION(91),
	TE_VIEW_LAST_MODIFIED_USER(92),
	TE_VIEW_LAST_MODIFIED_DATE(93),
	//TE_INSERTION(96),
	//TE_MODIFY(97),
	TE_SEARCH(98),
	TE_CLEAN(99),
	
	USER_VIEW_LOGIN(111),
	USER_VIEW_PASSWORD(112),
	USER_VIEW_RIGHTS(113),
	USER_ADD(114),
	USER_MODIFY(115),
	USER_REMOVE(116),
	USER_SEARCH(117),
	USER_CLEAR(118);
	
	private int index;
	
	private RightsFunction(int index) {
		this.index = index;
	}
	
	public int getValue() {
		return index;
	}
}
